# Generated by Django 2.1.3 on 2018-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181203_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('0', 'Not much'), ('1', 'Meh'), ('2', 'Maybe'), ('3', 'I could get down'), ('4', 'A must'), ('5', 'Yes, Yes, Yes')], max_length=200),
        ),
    ]
