# Generated by Django 2.1.3 on 2018-12-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181203_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='choices',
            field=models.CharField(choices=[('0', 'Not much'), ('1', 'Meh'), ('2', 'Maybe'), ('3', 'I could get down'), ('4', 'A must'), ('5', 'Yes, Yes, Yes')], default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
