# Generated by Django 2.1.3 on 2018-12-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181203_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(choices=[('0', 'Not much'), ('1', 'Meh'), ('2', 'Maybe'), ('3', 'I could get down'), ('4', 'A must'), ('5', 'Yes, Yes, Yes')], max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Movie'),
        ),
    ]
