# Generated by Django 2.1.3 on 2018-12-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181203_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.CharField(choices=[('0', 'No way'), ('1', 'Not really'), ('2', 'Meh'), ('3', 'Getting warmer'), ('4', 'Yes, on my radar'), ('5', 'A must see!')], max_length=1, null=True),
        ),
    ]
