# Generated by Django 2.1.3 on 2018-12-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181203_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
