# Generated by Django 2.1.4 on 2018-12-24 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_movie_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 14, 43, 24, 79364, tzinfo=utc)),
        ),
    ]
